#!/usr/bin/with-contenv bash

# TODO Need to install icu-dev (alpine) to work
# TODO Validate ubuntu install

## Ubuntu
if [ -f /usr/bin/apt ]; then
    cp -r /defaults/sqlite_icu/ubuntu/* /
fi

# Alpine
if [ -f /sbin/apk ]; then
    cp -r /defaults/sqlite_icu/alpine/* /
fi
