#!/usr/bin/with-contenv bash

## Ubuntu
if [ -f /usr/bin/apt ]; then
    cp -r /defaults/sqlite_icu/ubuntu/* /
    echo "\
        libicu74" >> /mod-repo-packages-to-install.list

fi

# Alpine
if [ -f /sbin/apk ]; then
    cp -r /defaults/sqlite_icu/alpine/* /
    echo "\
        icu-dev" >> /mod-repo-packages-to-install.list
fi
