#!/usr/bin/with-contenv bash

if [[ -n "$SQLITE_MIGRATE_DB" ]]; then
    if [[ -e ".sqlite_icu_extension_migrated" ]]; then
        echo "$SQLITE_MIGRATE_DB is already migrated, nothing to do"
        exit 0
    fi

    if [[ ! -e $SQLITE_MIGRATE_DB ]]; then
        echo "SQLITE_MIGRATE_DB=$SQLITE_MIGRATE_DB: file doesn't exist, exiting..."
        exit 1
    fi

    echo "**** Migrating $SQLITE_MIGRATE_DB  ****"
    cd $(dirname $SQLITE_MIGRATE_DB)

    DB=$(basename $SQLITE_MIGRATE_DB)
    UNMIGRATED="unmigrated_$DB"
    MIGRATED="migrated_$DB"

    # Backup DB
    cp $DB $UNMIGRATED
    echo "Backup DB saved at $UNMIGRATED"

    sqlite3 $DB -- .dump > dump.sql
    result=$?
    if [ "$result" != "0" ]; then
        echo "Dump failed"
        exit 1
    fi

    sqlite3 $MIGRATED -- '.read dump.sql'
    result=$?
    if [ "$result" != "0" ]; then
        echo "Restoring dump failed"
        exit 1
    fi

    echo "Overwriting old db..."
    mv $MIGRATED $DB

    cd -
    touch '.sqlite_icu_extension_migrated'
    echo "Successfully rebuilt $SQLITE_MIGRATE_DB with icu-extension!"
fi
